<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>Pixelizator</Product>
    <Description>Pixel art image studio</Description>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelArtDownscale\PixelArtDownscale.csproj" />
    <ProjectReference Include="..\PixelArtAlignment\PixelArtAlignment.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app-icon.png" />
    <Resource Include="Assets\landscape.png" />
  </ItemGroup>
</Project>
